# Generated by Django 5.2.4 on 2025-07-31 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_emailverificationotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('email', 'no-email@example.com'), _negated=True), fields=('user', 'email'), name='unique_user_email_resume'),
        ),
    ]
