# Generated by Django 5.2.4 on 2025-08-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_resume_fields_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
