# Generated by Django 5.2.4 on 2025-08-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_resume_experience_resume_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracurricular',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
