# Generated by Django 5.2.4 on 2025-07-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_resume_candidate_name_resume_education_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobdescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='home.jobdescription'),
        ),
    ]
