# Generated by Django 5.2.4 on 2025-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_resume_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
