# Generated by Django 5.2.4 on 2025-08-04 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_resume_extracurricular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resume',
            name='unique_user_email_resume',
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('email', 'no-email@example.com'), _negated=True), fields=('user', 'email', 'jobdescription'), name='unique_user_email_jd_resume'),
        ),
    ]
