# Generated by Django 5.2.4 on 2025-08-04 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_resume_unique_user_email_resume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('experience_gap', models.CharField(blank=True, max_length=255, null=True)),
                ('match_reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='home.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_results', to='home.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-overall_score'], name='home_matchi_user_id_b212b7_idx'), models.Index(fields=['job_description', '-overall_score'], name='home_matchi_job_des_837b2c_idx'), models.Index(fields=['-created_at'], name='home_matchi_created_bfbf7a_idx')],
                'unique_together': {('resume', 'job_description')},
            },
        ),
    ]
