# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_resume_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
