# Generated by Django 5.2.4 on 2025-08-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_matchingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
