# Generated by Django 5.2.4 on 2025-08-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_matchingresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingresult',
            name='email_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('selection_sent', 'Selection Email Sent'), ('rejection_sent', 'Rejection Email Sent')], default='not_sent', max_length=20),
        ),
    ]
