# Generated by Django 5.2.4 on 2025-08-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_matchingresult_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
