# Generated by Django 5.2.4 on 2025-08-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='List of interview questions with categories and purposes')),
                ('total_questions', models.IntegerField(help_text='Total number of questions generated')),
                ('estimated_duration', models.CharField(help_text='Estimated interview duration', max_length=20)),
                ('complexity_level', models.CharField(help_text='Interview complexity: junior, mid, senior', max_length=20)),
                ('focus_areas', models.JSONField(blank=True, help_text='Key areas the interview focuses on', null=True)),
                ('question_distribution', models.JSONField(blank=True, help_text='Number of questions per category', null=True)),
                ('status', models.CharField(choices=[('generated', 'Questions Generated'), ('reviewed', 'Reviewed by HR'), ('used', 'Used in Interview')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matching_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='home.matchingresult')),
            ],
            options={
                'verbose_name': 'Interview Questions',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['-generated_at'],
            },
        ),
    ]
