# Generated by Django 5.2.4 on 2025-08-30 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_interviewquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.EmailField(help_text="Candidate's email for verification", max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('session_token', models.CharField(help_text='Unique token for interview access', max_length=100, unique=True)),
                ('conversation_transcript', models.JSONField(default=list, help_text='Full conversation history')),
                ('questions_asked', models.JSONField(default=list, help_text='List of questions asked during interview')),
                ('candidate_responses', models.JSONField(default=list, help_text="Candidate's responses with metadata")),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total interview duration in seconds')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI evaluation score (0-100)', max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('technical_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_feedback', models.TextField(blank=True, help_text="AI's overall assessment", null=True)),
                ('strengths_identified', models.JSONField(default=list, help_text='Key strengths identified')),
                ('areas_for_improvement', models.JSONField(default=list, help_text='Areas needing improvement')),
                ('recommendation', models.CharField(blank=True, help_text='AI recommendation: proceed, maybe, reject', max_length=50, null=True)),
                ('audio_quality_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('connection_issues', models.JSONField(default=list, help_text='Any technical issues during interview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matching_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='home.matchingresult')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token'], name='home_interv_session_9b4e26_idx'), models.Index(fields=['candidate_email', '-created_at'], name='home_interv_candida_2c8e0f_idx'), models.Index(fields=['matching_result', '-created_at'], name='home_interv_matchin_e93ba4_idx')],
            },
        ),
    ]
