# Generated by Django 5.2.4 on 2025-09-05 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_interviewsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Interview Session', 'verbose_name_plural': 'Interview Sessions'},
        ),
        migrations.RemoveIndex(
            model_name='interviewsession',
            name='home_interv_session_9b4e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='interviewsession',
            name='home_interv_candida_2c8e0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='interviewsession',
            name='home_interv_matchin_e93ba4_idx',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='audio_quality_score',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='candidate_responses',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='communication_score',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='connection_issues',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='session_token',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='strengths_identified',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='technical_score',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_audio_quality',
            field=models.CharField(blank=True, help_text='Audio quality assessment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the interview', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='session_id',
            field=models.CharField(blank=True, help_text='WebSocket session identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='technical_issues',
            field=models.JSONField(blank=True, default=list, help_text='Any technical issues encountered'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions_planned',
            field=models.IntegerField(default=0, help_text='Total questions that were planned'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='conversation_transcript',
            field=models.JSONField(help_text='Complete conversation between AI and candidate'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='questions_asked',
            field=models.IntegerField(default=0, help_text='Number of questions asked'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['matching_result', '-started_at'], name='home_interv_matchin_b1572f_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['status'], name='home_interv_status_fc7ae1_idx'),
        ),
    ]
