# Generated by Django 5.2.4 on 2025-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_interviewsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='elevenlabs_conversation_id',
            field=models.CharField(blank=True, help_text='ElevenLabs conversation identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='elevenlabs_session_id',
            field=models.CharField(blank=True, help_text='ElevenLabs session identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_platform',
            field=models.CharField(default='elevenlabs', help_text='Platform used for interview (elevenlabs, deepgram, etc.)', max_length=50),
        ),
    ]
