# Generated by Django 5.2.4 on 2025-09-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_interviewsession_elevenlabs_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='elevenlabs_conversation_id',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='interview_platform',
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
