# Generated by Django 5.2.4 on 2025-09-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_interviewsession_elevenlabs_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='completion_reason',
            field=models.CharField(blank=True, help_text='Reason for interview completion (completed, user_ended, timeout, etc.)', max_length=100, null=True),
        ),
    ]
