# Generated by Django 5.2.4 on 2025-09-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_add_completion_reason_to_interview_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interview_audio/')),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='interview_transcripts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_data', models.JSONField(blank=True, null=True)),
                ('key_points', models.JSONField(blank=True, default=list, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matching_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_recording', to='home.matchingresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('user', 'Candidate'), ('assistant', 'Interviewer'), ('system', 'System')], max_length=20)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('sequence_number', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_message_data', models.JSONField(blank=True, null=True)),
                ('interview_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.interviewrecording')),
            ],
            options={
                'ordering': ['sequence_number', 'timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewrecording',
            index=models.Index(fields=['conversation_id'], name='home_interv_convers_83a0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewrecording',
            index=models.Index(fields=['status'], name='home_interv_status_22502c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewrecording',
            index=models.Index(fields=['created_at'], name='home_interv_created_0b7949_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['interview_recording', 'sequence_number'], name='home_interv_intervi_b73f45_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['speaker'], name='home_interv_speaker_d58d03_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['timestamp'], name='home_interv_timesta_0f0682_idx'),
        ),
    ]
