# Generated by Django 5.2.4 on 2025-09-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_interviewrecording_interviewmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Evaluation Pending'), ('in_progress', 'Evaluation In Progress'), ('completed', 'Evaluation Completed'), ('failed', 'Evaluation Failed')], default='pending', max_length=20)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('technical_knowledge_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('problem_solving_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cultural_fit_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enthusiasm_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recommendation', models.CharField(choices=[('strong_hire', 'Strong Hire - Proceed Immediately'), ('hire', 'Hire - Proceed to Next Round'), ('maybe', 'Maybe - Consider with Caution'), ('no_hire', 'No Hire - Do Not Proceed'), ('insufficient_data', 'Insufficient Data for Decision')], default='insufficient_data', max_length=30)),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('low', 'Low Confidence')], default='medium', max_length=20)),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of candidate strengths identified')),
                ('areas_of_concern', models.JSONField(blank=True, default=list, help_text='List of areas that need improvement or raise concerns')),
                ('key_insights', models.JSONField(blank=True, default=list, help_text='Important insights about the candidate')),
                ('communication_assessment', models.TextField(blank=True, help_text="Analysis of candidate's communication skills", null=True)),
                ('technical_assessment', models.TextField(blank=True, help_text='Analysis of technical knowledge and skills', null=True)),
                ('behavioral_assessment', models.TextField(blank=True, help_text='Analysis of behavioral responses and cultural fit', null=True)),
                ('questions_answered_well', models.JSONField(blank=True, default=list, help_text='Questions the candidate handled effectively')),
                ('questions_struggled_with', models.JSONField(blank=True, default=list, help_text='Questions the candidate had difficulty with')),
                ('recommended_next_steps', models.TextField(blank=True, help_text='Specific recommendations for next interview round', null=True)),
                ('topics_to_explore_further', models.JSONField(blank=True, default=list, help_text='Topics that need deeper exploration')),
                ('specific_concerns_to_address', models.JSONField(blank=True, default=list, help_text='Specific concerns to address in next round')),
                ('hr_reviewed', models.BooleanField(default=False, help_text='Whether HR has reviewed this evaluation')),
                ('hr_notes', models.TextField(blank=True, help_text='Additional notes from HR review', null=True)),
                ('hr_decision_override', models.CharField(blank=True, choices=[('strong_hire', 'Strong Hire - Proceed Immediately'), ('hire', 'Hire - Proceed to Next Round'), ('maybe', 'Maybe - Consider with Caution'), ('no_hire', 'No Hire - Do Not Proceed'), ('insufficient_data', 'Insufficient Data for Decision')], help_text='HR override of AI recommendation', max_length=30, null=True)),
                ('next_round_email_sent', models.BooleanField(default=False, help_text='Whether next round invitation email has been sent')),
                ('rejection_email_sent', models.BooleanField(default=False, help_text='Whether rejection email has been sent')),
                ('evaluation_duration_seconds', models.IntegerField(default=0, help_text='Time taken for AI evaluation')),
                ('evaluation_model_version', models.CharField(blank=True, help_text='Version of AI model used for evaluation', max_length=50, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, help_text='Raw response from AI evaluation agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('interview_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='home.interviewrecording')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='home_interv_status_c2205d_idx'), models.Index(fields=['recommendation'], name='home_interv_recomme_f5737b_idx'), models.Index(fields=['overall_score'], name='home_interv_overall_542101_idx'), models.Index(fields=['hr_reviewed'], name='home_interv_hr_revi_96079d_idx'), models.Index(fields=['created_at'], name='home_interv_created_21bea0_idx')],
            },
        ),
    ]
