# Generated by Django 5.2.4 on 2025-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_add_simplified_evaluation_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecording',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='email_type',
            field=models.CharField(blank=True, choices=[('selection', 'Selection'), ('rejection', 'Rejection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='interview_round',
            field=models.CharField(blank=True, choices=[('initial', 'Initial Interview'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('final', 'Final Interview')], max_length=20, null=True),
        ),
    ]
