# Generated by Django 5.2.4 on 2025-09-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_interviewrecording_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecording',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='interview_location',
            field=models.TextField(blank=True, help_text='Office address for onsite interviews', null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Zoom meeting ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom meeting link for online interviews', null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='meeting_password',
            field=models.CharField(blank=True, help_text='Zoom meeting password', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_address',
            field=models.TextField(blank=True, help_text='Default office address for onsite interviews', null=True),
        ),
    ]
