# Generated by Django 5.2.4 on 2025-09-16 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_interviewrecording_interview_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(default='initial_complete', max_length=50)),
                ('pipeline_status', models.CharField(choices=[('initial_complete', 'Initial Interview Complete'), ('in_pipeline', 'In Interview Pipeline'), ('ready_for_onboarding', 'Ready for Onboarding'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Candidate Withdrawn')], default='initial_complete', max_length=30)),
                ('meets_onboarding_criteria', models.BooleanField(default=False)),
                ('onboarding_email_sent', models.BooleanField(default=False)),
                ('onboarding_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('hr_notes', models.TextField(blank=True, help_text='Internal HR notes about candidate')),
                ('interview_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_status', to='home.interviewrecording')),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('final', 'Final Interview'), ('panel', 'Panel Interview'), ('cultural_fit', 'Cultural Fit Interview')], max_length=20)),
                ('stage_order', models.IntegerField(default=1, help_text='Order of this stage in pipeline')),
                ('interview_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Interview duration in minutes')),
                ('overall_score', models.FloatField(default=0.0, help_text='Score out of 10')),
                ('technical_skills_score', models.FloatField(default=0.0, help_text='Technical competency (0-10)')),
                ('communication_score', models.FloatField(default=0.0, help_text='Communication skills (0-10)')),
                ('cultural_fit_score', models.FloatField(default=0.0, help_text='Cultural fit (0-10)')),
                ('problem_solving_score', models.FloatField(default=0.0, help_text='Problem solving ability (0-10)')),
                ('strengths', models.TextField(blank=True, help_text="Candidate's key strengths")),
                ('weaknesses', models.TextField(blank=True, help_text='Areas for improvement')),
                ('notes', models.TextField(blank=True, help_text='Additional interview notes')),
                ('recommendation', models.CharField(choices=[('reject', 'Reject'), ('on_hold', 'On Hold'), ('proceed', 'Proceed to Next Stage'), ('hire', 'Recommend for Hire')], default='proceed', max_length=20)),
                ('recommendation_notes', models.TextField(blank=True, help_text='Reasoning for recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_stages', to='home.interviewrecording')),
                ('interviewer', models.ForeignKey(help_text='HR/Manager who conducted interview', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['interview_recording', 'stage_order'],
                'unique_together': {('interview_recording', 'stage_type')},
            },
        ),
    ]
