# Generated by Django 5.2.4 on 2025-09-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_candidatepipeline_interviewstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewstage',
            options={'ordering': ['interview_recording', 'created_at']},
        ),
        migrations.RenameField(
            model_name='interviewstage',
            old_name='notes',
            new_name='additional_notes',
        ),
        migrations.RenameField(
            model_name='interviewstage',
            old_name='weaknesses',
            new_name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='candidatepipeline',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='candidatepipeline',
            name='meets_onboarding_criteria',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='recommendation_notes',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='stage_order',
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='adaptability_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Adaptability (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='coding_skills_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Coding skills (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='leadership_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Leadership potential (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='overall_assessment_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Overall assessment (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='strategic_thinking_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Strategic thinking (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='teamwork_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Teamwork ability (0-10)', null=True),
        ),
        migrations.AlterField(
            model_name='candidatepipeline',
            name='pipeline_status',
            field=models.CharField(choices=[('active', 'Active in Pipeline'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Candidate Withdrawn')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='communication_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Communication skills (0-10)', null=True),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='cultural_fit_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Cultural fit (0-10)', null=True),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Interview duration in minutes'),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='problem_solving_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Problem solving ability (0-10)', null=True),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='stage_type',
            field=models.CharField(choices=[('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('final', 'Final Interview')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='technical_skills_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Technical competency (0-10)', null=True),
        ),
    ]
