# Generated by Django 5.2.4 on 2025-09-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_interviewstage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewstage',
            options={'ordering': ['interview_recording', 'stage_order']},
        ),
        migrations.RenameField(
            model_name='interviewstage',
            old_name='additional_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='interviewstage',
            old_name='areas_for_improvement',
            new_name='weaknesses',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='adaptability_score',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='coding_skills_score',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='leadership_score',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='overall_assessment_score',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='strategic_thinking_score',
        ),
        migrations.RemoveField(
            model_name='interviewstage',
            name='teamwork_score',
        ),
        migrations.AddField(
            model_name='candidatepipeline',
            name='current_stage',
            field=models.CharField(default='initial_complete', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatepipeline',
            name='meets_onboarding_criteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='overall_score',
            field=models.FloatField(default=0.0, help_text='Score out of 10'),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='recommendation_notes',
            field=models.TextField(blank=True, help_text='Reasoning for recommendation'),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='stage_order',
            field=models.IntegerField(default=1, help_text='Order of this stage in pipeline'),
        ),
        migrations.AlterField(
            model_name='candidatepipeline',
            name='pipeline_status',
            field=models.CharField(choices=[('initial_complete', 'Initial Interview Complete'), ('in_pipeline', 'In Interview Pipeline'), ('ready_for_onboarding', 'Ready for Onboarding'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected'), ('withdrawn', 'Candidate Withdrawn')], default='initial_complete', max_length=30),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='communication_score',
            field=models.FloatField(default=0.0, help_text='Communication skills (0-10)'),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='cultural_fit_score',
            field=models.FloatField(default=0.0, help_text='Cultural fit (0-10)'),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Interview duration in minutes'),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='problem_solving_score',
            field=models.FloatField(default=0.0, help_text='Problem solving ability (0-10)'),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='stage_type',
            field=models.CharField(choices=[('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('final', 'Final Interview'), ('panel', 'Panel Interview'), ('cultural_fit', 'Cultural Fit Interview')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='technical_skills_score',
            field=models.FloatField(default=0.0, help_text='Technical competency (0-10)'),
        ),
    ]
